name: OldCombatMechanics
main: kernitus.plugin.OldCombatMechanics.OCMMain
version: 2.3.0-adapted
api-version: 1.19

dependencies:
  server:
    ProtocolLib:
      required: false
      load: BEFORE
    ViaVersion:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE