name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    # This permission is still required by the new action
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    # Build Step - No changes needed here
    - name: Run Gradle Build
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}  # Strip 'v' if present
          ./gradlew clean build -Pversion=$VERSION
        else
          ./gradlew clean build
        fi
        
    - name: Rename Release Asset
      if: ${{ github.event_name == 'release' }}
      run: mv ./build/libs/OldCombatMechanics.jar ./build/libs/OldCombatMechanics-${{ github.event.release.tag_name }}.jar

    - name: Upload Artifact to GitHub Release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v2
      with:
        # The 'files' input takes a path to the asset(s) you want to upload.
        # We point it to the newly renamed JAR file.
        files: ./build/libs/OldCombatMechanics-${{ github.event.release.tag_name }}.jar

    - name: Read game versions from gradle.properties
      run: |
        GAME_VERSIONS=$(grep ^gameVersions gradle.properties | cut -d'=' -f2-)
        echo "GAME_VERSIONS=$GAME_VERSIONS" >> $GITHUB_ENV
        
    - name: Upload to dev.bukkit.org
      if: ${{ github.event_name == 'release' }}
      uses: benwoo1110/dbo-upload-action@main
      with:
        api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
        project_id: '98233'
        changelog: ${{ github.event.release.body }}
        changelog_type: markdown
        display_name: OldCombatMechanics ${{ github.event.release.tag_name }}
        game_versions: ${{ env.GAME_VERSIONS }}
        # IMPORTANT: Update the file_path to use the renamed JAR
        file_path: './build/libs/OldCombatMechanics-${{ github.event.release.tag_name }}.jar'


    - name: Publish to Hangar
      env:
        HANGAR_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        HANGAR_CHANGELOG: ${{ github.event.release.body }}
      run: ./gradlew build publishPluginPublicationToHangar --stacktrace
